### ISSUE TITLE
redis cache failing to correctly unserialize guild members

### ISSUE THREAD

**Issue by Skelmis** [Skelmis/Discord-Anti-Spam#103]
**Describe the bug**
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/core.py", line 87, in propagate_user
    member: Member = await self.cache.get_member(
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/caches/redis/redis.py", line 102, in get_member   
    raise MemberNotFound
antispam.exceptions.MemberNotFound: A Member matching this id and guild id could not be found in the cache.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/discord/client.py", line 393, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/better-altdetect/sentinel/events.py", line 23, in on_message
    await self.spam_handler.propagate(msg)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/anti_spam_handler.py", line 71, in wrapper        
    return await func(*args, **kwargs)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/anti_spam_handler.py", line 306, in propagate     
    main_return = await self.core.propagate(message, guild=guild)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/core.py", line 70, in propagate
    guild_r = await self.propagate_user(message, guild)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/core.py", line 105, in propagate_user
    guild.members[member.id] = member
IndexError: list assignment index out of range
```

**Enviroment**
 - Package Version: [e.g. 0.1.1] 

**Additional context**
Reported via discord

**Comment by CraziiAce** [comment]
As for this issue, this only happens when the guild settings are not yet in the redis cache. Here's a little screen capture showing the  redis keys before & after sending the first message after dumping all the keys:
![1fc79b798321e061692841cc8573c269](https://user-images.githubusercontent.com/63609284/173734201-be1656ca-05b1-45d3-aa05-8262ab22b1bf.png)
After this, once the guild settings are already in the cache, I get #104.
What I think is happening is you are trying to use `guild.members` as a dict of `{int: discord.Member}`, (see [discord.py's docs](https://discordpy.readthedocs.io/en/latest/api.html#discord.Guild.members)) instead of using `guild.fetch_member`.
Please correct me if I am wrong, as I'm not super familiar with how this package works.
If this is the case, I can make a PR and fix it.

**Comment by CraziiAce** [comment]
Well, for some reason I don't seem to get that error anymore, but we have this related one:
```
03:27 PM on June 15 2022:INFO: antispam.anti_spam_handler: Init has been called, everything is now definitely setup.
03:27 PM on June 15 2022:INFO: antispam.anti_spam_handler: Propagating message for i like waffles(555709231697756160) in guild(982861623360389140)
03:27 PM on June 15 2022:DEBUG: antispam.caches.redis.redis: Attempting to return cached Guild(id=982861623360389140)
{}
03:27 PM on June 15 2022:DEBUG: antispam.caches.redis.redis: Attempting to set Guild(id=982861623360389140)
Guild members from within function:{}
is a dict
03:27 PM on June 15 2022:INFO: antispam.anti_spam_handler: Created Guild(id=982861623360389140)
03:27 PM on June 15 2022:DEBUG: antispam.caches.redis.redis: Attempting to return a cached Member(id=555709231697756160) for Guild(id=982861623360389140)
is dataclasses guild
[]
03:27 PM on June 15 2022:DEBUG: antispam.caches.redis.redis: Attempting to set Guild(id=982861623360389140)
Guild members from within function:[]
is a list
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/core.py", line 88, in propagate_user
    member: Member = await self.cache.get_member(
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/caches/redis/redis.py", line 108, in get_member   
    raise MemberNotFound
antispam.exceptions.MemberNotFound: A Member matching this id and guild id could not be found in the cache.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/discord/client.py", line 393, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/better-altdetect/sentinel/events.py", line 23, in on_message
    await self.spam_handler.propagate(msg)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/anti_spam_handler.py", line 71, in wrapper        
    return await func(*args, **kwargs)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/anti_spam_handler.py", line 306, in propagate     
    main_return = await self.core.propagate(message, guild=guild)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/core.py", line 71, in propagate
    guild_r = await self.propagate_user(message, guild)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/core.py", line 113, in propagate_user
    await self.cache.set_guild(guild=guild)
  File "/home/ubuntu/better-altdetect/venv/lib/python3.10/site-packages/antispam/caches/redis/redis.py", line 89, in set_guild     
    for member in guild.members.values():
AttributeError: 'list' object has no attribute 'values
```
You can see some of my debug code in there. After some debugging, I narrowed the problem down to the `set_guild` function (see [here](https://github.com/Skelmis/Discord-Anti-Spam/blob/master/antispam/caches/redis/redis.py#L80-L88)). For whatever reason, the function is called twice. The first time, guild.members is an empty dict, so on lines [83 & 84](https://github.com/Skelmis/Discord-Anti-Spam/blob/master/antispam/caches/redis/redis.py#L83-L84), the function tries to iterate through it, but stops instantly because there are no keys nor values. For some reason, the function is called a second time, and this time guild.members is equal to a list. Either way, at no point in time does guild.members actually contain any members.

If it helps, here is what I added to `set_guild`:
```py
async def set_guild(self, guild: Guild) -> None:
    log.debug("Attempting to set Guild(id=%s)", guild.id)
    # Store members separate

    print("Guild members from within function:" + str(guild.members))
    if isinstance(guild.members, dict):
        print("is a dict")
    elif isinstance(guild.members, list):
        print("is a list")
    for member in guild.members.values():
        await self.set_member(member)

    guild.members = [member.id for member in guild.members.values()]
    as_json = json.dumps(asdict(guild, recurse=True))
    await self.redis.set(f"GUILD:{guild.id}", as_json)
```

Both times the function is called from [here](https://github.com/Skelmis/Discord-Anti-Spam/blob/master/antispam/anti_spam_handler.py#L251-L262), and because `guild.members` isn't automatically set to the actual dict of members when you create the guild, it is always empty.

If the members aren't already set and you have no other way of getting them other than from the cache, then you obviously can't iterate through them.

As stated earlier, I'm not very sure of exactly how your library works, so please correct me if I am wrong.

Maybe a good way to fix this would be to add a `get_members` function to the library which for discord.py would just return [discord.Message.guikd](https://discordpy.readthedocs.io/en/latest/api.html#discord.Message.guild), and I'm sure there are alternatives for the other libraries

**Comment by Skelmis** [comment]
We maintain our own state, I won't be planning on populating entire custom data structures due to a logic bug any time soon. That's also a very expensive partial fix in terms of the required memory (compared to now) and ensuring it is kept up to date.

Internally the redis cache is kept seperate between Members and Guilds for historical purposes, and reducing required serialization for small edits which is why it ends up as a list of member IDs.
This distinction works as intended for Mongo, so it's likely I've just broken something here and didn't realize during my own usage.

**Comment by CraziiAce** [comment]
Could redis just use roughly the same implementation of set_guild that the mongo/memory caches do? I don't think it would be a super difficult fix.

**Comment by Skelmis** [comment]
Yes, it is essentially the same outside of the list now anyway.

**Comment by Skelmis** [comment]
This *should* be fixed as a side effect of the work I've just completed on the redis cache
