### ISSUE TITLE
Pycord support

### ISSUE THREAD

**Issue by Nzii3** [Skelmis/Discord-Anti-Spam#106]
Does this library support Pycord as the `library` parameter? Or does it only support discord.py?

**Comment by Skelmis** [comment]
You can find that information in the documentation linked [here](https://dpy-anti-spam.readthedocs.io/en/latest/modules/interactions/enums.html#antispam.enums.Library)

**Comment by Nzii3** [comment]
@Skelmis I used that and I got an error that the PYCORD enum wasn’t supported anymore.

**Comment by Skelmis** [comment]
And it also provides instructions for usage among other things in that error.

**Comment by Nzii3** [comment]
All it shows is the enum types

**Comment by Skelmis** [comment]
Running it with the pycord enum would provide the link, however, you can find that document [here](https://gist.github.com/Skelmis/b15a64f11c2ef89a7c6083ff455774a2)

**Comment by Nzii3** [comment]
With all due respect, but that’s not a valid reason to not support them anymore, I do agree that they shouldn’t have taken ALL the credit and been taking donations. However, they didn’t ask for the donations, they didn’t ask for people to donate. People decided to donate. Danny is now maintaining discord.py again, as they probably expected he would come back so they didn’t want Pycord to basically be praising Danny for his amazing work. Danny made the repository public and didn’t ask for people to “praise” him.

With that aside, I do have a suggestion:
> Be able to set custom functions for events punishments. Or have an event called to where we can set those callbacks. Mainly more customizations.

**Comment by Skelmis** [comment]
I'll address this as separate comments.

1. That is quite the assumption to make, that I dropped supported **only** due to donations. It is also an assumption that is incorrect. Donations are only 1 bullet point in that internal list, there are about ~10 points as of the last time I revised it.
2. With all due respect, this is my library. I am under no obligations, contractual or otherwise, to support third-party software for simply existing. This software is licensed and provided "AS IS", and I don't even have to include the gist which *does* provide end-users with a way to use this with py-cord. It could have simply been marked as a breaking change and just left
3. I would prefer if feature requests were separate issues, however, I will address it here. I have no plans to implement something like that, there already exist mechanisms that allow end-users to implement custom punishments as they see fit.  See options such as `no_punish` and `AntiSpamTracker`. If you wish to get help with this specifically, feel free to join the support discord.

**Comment by Nzii3** [comment]
Alright, I understand your point. And yes, it’s your library.

**Comment by Nzii3** [comment]
So would I do the library type as dpy?

**Comment by Nzii3** [comment]
And I am getting this error when I followed all the steps
![336891CE-0021-435F-BBFD-E78587D5AFEC](https://user-images.githubusercontent.com/106406461/176334371-49fc0249-ef56-458d-8cb8-c8ed72d84dad.jpeg)

**Comment by Skelmis** [comment]
a) If you want timeouts, use what it states in the gist.
b) Install it, looks I missed it in the deps
c) For further things please join the support discord as this is moving off topic + its easier for me
